name: Sync Fork

on:
  schedule:
    - cron: "10 7 * * *"  # 每天 14:55 (UTC+8) 执行一次
  push:
    branches:
      - main
  workflow_dispatch:  # 允许手动触发工作流

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Fork
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config user.name "klcb2010"
          git config user.email "klcb2010@gmail.com"

      - name: Add Original Repo as Remote
        run: git remote add upstream https://github.com/qxzg/Actions.git

      - name: Fetch Upstream Changes
        run: git fetch upstream

      - name: Merge Upstream Changes
        run: git merge upstream/main --allow-unrelated-histories -m "Syncing with upstream"

      - name: Push Changes to Fork
        run: git push origin main

      - name: Record Last Sync Time
        run: |
          echo "Last sync: $(date)" > sync_log.txt  # 记录当前时间
        shell: bash

      - name: Commit Sync Log
        run: |
          git add sync_log.txt
          git diff --cached --quiet || (git commit -m "Update sync log with last sync time" && git push origin main)
