name: Sync Fork

on:
  schedule:
    - cron: "55 6 * * *"  # 每天 14:55 (UTC+8) 执行一次
  push:
    branches:
      - main
  workflow_dispatch:  # 允许手动触发工作流

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Fork
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config user.name "Your Name"
          git config user.email "your-email@example.com"

      - name: Add Original Repo as Remote
        run: git remote add upstream https://github.com/qxzg/Actions.git

      - name: Fetch Upstream Changes
        run: |
          git fetch upstream  # 获取 upstream 的所有更新
          git branch -r  # 查看远程分支

      - name: Checkout Upstream/3.0 Branch
        run: git checkout upstream/3.0  # 直接切换到 upstream 的 3.0 分支

      - name: Copy 'fancyss_rules' directory from upstream
        run: |
          # 从 upstream 的 3.0 分支中拉取 fancyss_rules 目录到当前工作目录
          git checkout upstream/3.0 -- fancyss_rules

      - name: Commit Changes
        run: |
          git add fancyss_rules
          git commit -m "Syncing fancyss_rules from upstream" || echo "No changes to commit"  # 如果没有更改，则跳过
          git push origin main  # 将更新推送到自己的 fork

      - name: Record Last Sync Time
        run: |
          echo "Last sync: $(date)" > sync_log.txt  # 记录当前时间
        shell: bash

      - name: Commit Sync Log
        run: |
          git add sync_log.txt
          git diff --cached --quiet || (git commit -m "Update sync log with last sync time" && git push origin main)
